
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('chapter_service').del()
    .then(function () {
      // Inserts seed entries
      return knex('chapter_service').insert([
        {Chapter: "YWCA Rock County", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Brooklyn", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Greater Lafayette", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Greater Miami-Dade", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Princeton", Service: 'Citizenship Classes'},
        {Chapter: "YWCA San Antonio", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Tri-County Area", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Tulsa", Service: 'Citizenship Classes'},
        {Chapter: "YWCA Annapolis", Service: 'Community Service Provider'},
        {Chapter: "YWCA Central Carolinas", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Johnstown ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Jamestown", Service: 'Community Service Provider'},
        {Chapter: "YWCA Nashville & Middle Tennessee", Service: 'Community Service Provider'},
        {Chapter: "YWCA Northwest Indiana", Service: 'Community Service Provider'},
        {Chapter: "YWCA Rock County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Yakima", Service: 'Community Service Provider'},
        {Chapter: "YWCA Beaumont", Service: 'Community Service Provider'},
        {Chapter: "YWCA Bellingham", Service: 'Community Service Provider'},
        {Chapter: "YWCA Billings", Service: 'Community Service Provider'},
        {Chapter: "YWCA Black Hawk County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Boulder County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Brooklyn", Service: 'Community Service Provider'},
        {Chapter: "YWCA BUCKS ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Cambridge", Service: 'Community Service Provider'},
        {Chapter: "YWCA Canton, Canton, Ohio", Service: 'Community Service Provider'},
        {Chapter: "YWCA Carlisle", Service: 'Community Service Provider'},
        {Chapter: "YWCA Central Indiana", Service: 'Community Service Provider'},
        {Chapter: "YWCA Central Mass.", Service: 'Community Service Provider'},
        {Chapter: "YWCA Charleston, WV", Service: 'Community Service Provider'},
        {Chapter: "YWCA Clark County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Columbus", Service: 'Community Service Provider'},
        {Chapter: "YWCA Dayton ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Delaware", Service: 'Community Service Provider'},
        {Chapter: "YWCA Duluth", Service: 'Community Service Provider'},
        {Chapter: "YWCA El Paso del Norte Region", Service: 'Community Service Provider'},
        {Chapter: "ywca elyria", Service: 'Community Service Provider'},
        {Chapter: "YWCA Elyria", Service: 'Community Service Provider'},
        {Chapter: "YWCA Evanston/North Shore", Service: 'Community Service Provider'},
        {Chapter: "YWCA Gettysburg & Adams County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Great Falls", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Baton Rouge ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Cincinnati", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Lafayette", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Los Angeles", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Miami-Dade", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greater Pittsburgh", Service: 'Community Service Provider'},
        {Chapter: "YWCA Green Bay ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Greenwich", Service: 'Community Service Provider'},
        {Chapter: "YWCA Knoxville & the Tennessee Valley", Service: 'Community Service Provider'},
        {Chapter: "YWCA La Crosse", Service: 'Community Service Provider'},
        {Chapter: "YWCA Lancaster", Service: 'Community Service Provider'},
        {Chapter: "YWCA Lewiston, ID-Clarkston, WA", Service: 'Community Service Provider'},
        {Chapter: "YWCA Lowell", Service: 'Community Service Provider'},
        {Chapter: "YWCA Madison", Service: 'Community Service Provider'},
        {Chapter: "YWCA Metropolitan Chicago ", Service: 'Community Service Provider'},
        {Chapter: "YWCA Minot", Service: 'Community Service Provider'},
        {Chapter: "ywca north central washington", Service: 'Community Service Provider'},
        {Chapter: "YWCA Northeast Kansas", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Fort Dodge", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Greater Atlanta", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Houston", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Lubbock", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Queens", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Syracuse and Onondaga County Inc.", Service: 'Community Service Provider'},
        {Chapter: "YWCA of the City of New York", Service: 'Community Service Provider'},
        {Chapter: "YWCA of the Upper Lowlands, Inc.", Service: 'Community Service Provider'},
        {Chapter: "YWCA of Winston Salem", Service: 'Community Service Provider'},
        {Chapter: "YWCA Oklahoma City", Service: 'Community Service Provider'},
        {Chapter: "YWCA Olympia", Service: 'Community Service Provider'},
        {Chapter: "YWCA Orange County", Service: 'Community Service Provider'},
        {Chapter: "YWCA Rhode Island", Service: 'Community Service Provider'},
        {Chapter: "YWCA San Antonio", Service: 'Community Service Provider'},
        {Chapter: "YWCA Sauk Valley", Service: 'Community Service Provider'},
        {Chapter: "YWCA Seattle/King/Snohomish", Service: 'Community Service Provider'},
        {Chapter: "Ywca Southern Arizona", Service: 'Community Service Provider'},
        {Chapter: "YWCA Tri-County Area", Service: 'Community Service Provider'},
        {Chapter: "YWCA Tulsa", Service: 'Community Service Provider'},
        {Chapter: "YWCA ULSTER COUNTY", Service: 'Community Service Provider'},
        {Chapter: "YWCA Western New York", Service: 'Community Service Provider'},
        {Chapter: "YWCA Westfield", Service: 'Community Service Provider'},
        {Chapter: "YWCA Wheeling", Service: 'Community Service Provider'},
        {Chapter: "YWCA York", Service: 'Community Service Provider'},
        {Chapter: "YWCA Central Carolinas", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Central Virginia", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Harrisburg", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Jamestown", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Nashville & Middle Tennessee", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Northwest Ohio", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Pierce County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Rock County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Silicon Valley", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Southeastern Massachusetts", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA University of Illinois", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA WATSONVILLE ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Wausau", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Yakima", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Allentown", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Asheville", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Bergen County ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Boston", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Boulder County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Brooklyn", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Canton IL", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Carlisle", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Cass Clay", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Central Mass.", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Charleston, WV", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Clark County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Dayton ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Delaware", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA El Paso del Norte Region", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Elgin", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "ywca elyria", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Elyria", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Enid", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Evanston/North Shore", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Gettysburg & Adams County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Great Falls", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Austin", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Baton Rouge ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Cincinnati", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Cleveland", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Lafayette", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Pittsburgh", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greater Portland", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Greenwich", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Hamilton", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Kalamazoo", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Knoxville & the Tennessee Valley", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA La Crosse", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Lake County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Lancaster", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Lincoln", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Lowell", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Lower Cape Fear", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Madison", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Malden", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Mankato", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Metropolitan Chicago ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Minneapolis", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Missoula", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Monterey County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA National Capital Area", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA New Britain", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA North Central Indiana", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "ywca north central washington", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Northeast Indiana", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Northeast Kansas", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Northeastern Massachusetts", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Northwestern Ilinois", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Fort Dodge", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Kitsap County ", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Marshalltown, IA", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of North Orange County DBA: YWCA Orange County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Queens", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Rochester & Monroe County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of San Gabriel Valley", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Syracuse and Onondaga County Inc.", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of Winston Salem", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA of WSU", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Oklahoma City", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Olympia", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Olympia", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Orange County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Princeton", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Rhode Island", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Richmond (VA)", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA San Franciso", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Sauk Valley", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Seattle/King/Snohomish", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA South Hampton Roads", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "Ywca Southern Arizona", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA St. Paul", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Tri-County Area", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Tulsa", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Union County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Walla Walla", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA West Central Michigan", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Westmoreland County", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA Wheeling", Service: 'Cultural Competency Work (internal)'},
        {Chapter: "YWCA York", Service: 'Cultural Competency Work (internal)'},        
        {Chapter: "YWCA Greater Harrisburg", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Jamestown", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Nashville & Middle Tennessee", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Northwest Ohio", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Rock County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Southeastern Massachusetts", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Wausau", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Yakima", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Asheville", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Bergen County ", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Boston", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Boulder County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Canton IL", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Carlisle", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Central Mass.", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Charleston, WV", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Clark County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "ywca elyria", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Elyria", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Enid", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Evanston/North Shore", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Gettysburg & Adams County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Austin", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Cincinnati", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Cleveland", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Lafayette", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Pittsburgh", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Greater Portland", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Green Bay ", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA High Point", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Kalamazoo", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA La Crosse", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Lake County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Lincoln", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Lowell", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Lower Cape Fear", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Madison", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Metropolitan Chicago ", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Minneapolis", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Missoula", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA National Capital Area", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA New Britain", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "ywca north central washington", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Northeast Indiana", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Northeast Kansas", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Northeastern Massachusetts", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Northwestern Ilinois", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA of Greater Atlanta", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA of Marshalltown, IA", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA of Mount Desert Island", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA of Queens", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA of San Gabriel Valley", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Oklahoma City", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Olympia", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Olympia", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Orange County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Rhode Island", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA San Franciso", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Sauk Valley", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "Ywca Southern Arizona", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Tri-County Area", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Tulsa", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Union County", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA Wheeling", Service: 'Cultural Competency Work (external)'},        
        {Chapter: "YWCA York", Service: 'Cultural Competency Work (external)'},
        {Chapter: "YWCA Bethlehem", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Central Carolinas", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Metropolitan Phoenix", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Northwest Ohio", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Palm Beach", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Pierce County", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Southeast Wisconsin", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Titusville", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA WATSONVILLE ", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Wausau", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA White Plains &Central Westchester", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Yakima", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Alaska", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Ames-ISU", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Bergen County ", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Berkeley/Oakland", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Boston", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Bradford", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Carlisle", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Cass Clay", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Charleston, WV", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Clinton", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Columbus", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Corpus Christi", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Cortland", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Dayton ", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Delaware", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA El Paso del Norte Region", Service: 'Dialogues / Study Circles'},
        {Chapter: "ywca elyria", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Elyria", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Enid", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Evanston/North Shore", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Gettysburg & Adams County", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Great Falls", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Austin", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Baton Rouge ", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Cincinnati", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Cleveland", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Los Angeles", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greater Miami-Dade", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Greenwich", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Hamilton", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Helena", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA La Crosse", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Lake County", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Lancaster", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Lowell", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Lower Cape Fear", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Mankato", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Metro St. Louis", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Minneapolis", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA National Capital Area", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA North Central Indiana", Service: 'Dialogues / Study Circles'},
        {Chapter: "ywca north central washington", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Northeast Indiana", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Northeast Kansas", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Alton", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Genesee County", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Greater Atlanta", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Kauai", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Mount Desert Island", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of Northwest Louisiana", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of the City of New York", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA of WSU", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Olympia", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Olympia", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Pasadena-Foothill Valley", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Princeton", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Quad Cities", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Rhode Island", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Seattle/King/Snohomish", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA South Hampton Roads", Service: 'Dialogues / Study Circles'},
        {Chapter: "Ywca Southern Arizona", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Spokane", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA St. Paul", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA SWVA and NETN", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Westmoreland County", Service: 'Dialogues / Study Circles'},
        {Chapter: "YWCA Wheeling", Service: 'Dialogues / Study Circles'},
        
      ]);
    });
};
