
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('services').del()
    .then(function () {
      // Inserts seed entries
      return knex('services').insert([
        {Name: "Citizenship Classes",Category:"Racial Justice and Civil Rights"},
        {Name: "Community Service Provider",Category:"Racial Justice and Civil Rights"},
        {Name: "Cultural Competency Work (internal)",Category:"Racial Justice and Civil Rights"},
        {Name: "Cultural Competency Work (external)",Category:"Racial Justice and Civil Rights"},
        {Name: "Dialogues / Study Circles",Category:"Racial Justice and Civil Rights"},
        {Name: "Employer Training Program",Category:"Racial Justice and Civil Rights"},
        {Name: "English as a Second Language",Category:"Racial Justice and Civil Rights"},
        {Name: "Immigrant/Refugee Services",Category:"Racial Justice and Civil Rights"},
        {Name: "Public Policy",Category:"Racial Justice and Civil Rights"},
        {Name: "Racial Justice Center",Category:"Racial Justice and Civil Rights"},
        {Name: "Restorative Justice",Category:"Racial Justice and Civil Rights"},
        {Name: "Training",Category:"Racial Justice and Civil Rights"},
        {Name: "Translation Services	",Category:"Racial Justice and Civil Rights"},
        {Name: "Voter Education/Registration",Category:"Racial Justice and Civil Rights"},
        {Name: "Empowerment Programs for Youth and Adults of Color",Category:"Racial Justice and Civil Rights"},
        {Name: "Hotline	Crisis Response	Survivor Advocacy / Legal Advocacy",Category:"Domestic Violence"},
        {Name: "Emergency Shelter",Category:"Domestic Violence"},
        {Name: "Transitional Housing",Category:"Domestic Violence"},
        {Name: "Counseling",Category:"Domestic Violence"},
        {Name: "Children’s Services",Category:"Domestic Violence"},
        {Name: "Prevention Education",Category:"Domestic Violence"},
        {Name: "Community Education",Category:"Domestic Violence"},
        {Name: "Perpetrator Services",Category:"Domestic Violence"},
        {Name: "Family Justice Centers",Category:"Domestic Violence"},
        {Name: "Supervised Visitation",Category:"Domestic Violence"},
        {Name: "Personal Financial Literacy",Category:"Domestic Violence"},
        {Name: "Job/Work Skills Training",Category:"Domestic Violence"},
        {Name: "Military Survivors",Category:"Domestic Violence"},
        {Name: "Trauma Informed Care and Case Management/Referral",Category:"Domestic Violence"},
        {Name: "Counseling",Category:"Sexual Assault"},
        {Name: "Crisis Response",Category:"Sexual Assault"},
        {Name: "Hotline",Category:"Sexual Assault"},
        {Name: "Survivor Advocacy / Legal Advocacy",Category:"Sexual Assault"},
        {Name: "Nurse Examiner Training",Category:"Sexual Assault"},
        {Name: "Emergency Shelter",Category:"Sexual Assault"},
        {Name: "Trafficking	Outreach / Prevention / Education",Category:"Sexual Assault"},
        {Name: "Case Management",Category:"Sexual Assault"},
        {Name: "Perpetrator Services",Category:"Sexual Assault"},
        {Name: "Military Survivors",Category:"Sexual Assault"},
        {Name: "Trauma Informed Care and Case Management/Referral",Category:"Sexual Assault"},
        {Name: "Rapid Rehousing",Category:"Housing"},
        {Name: "Family Housing",Category:"Housing"},
        {Name: "Landlord Liaison Programs",Category:"Housing"},
        {Name: "Longer term, affordable (no support services)",Category:"Housing"},
        {Name: "Longer term, affordable (support services)",Category:"Housing"},
        {Name: "Military",Category:"Housing"},
        {Name: "Senior	Shelter (short-term)",Category:"Housing"},
        {Name: "Teen Housing",Category:"Housing"},
        {Name: "Transitional",Category:"Housing"},
        {Name: "Anti-Bullying",Category:"Child Care and Child Development"},
        {Name: "Head Start",Category:"Child Care and Child Development"},
        {Name: "Infant/Toddler",Category:"Child Care and Child Development"},
        {Name: "Pre-Kindergarten",Category:"Child Care and Child Development"},
        {Name: "Kindergarten",Category:"Child Care and Child Development"},
        {Name: "Parenting Programs Family Support Programs",Category:"Child Care and Child Development"},
        {Name: "School-Age: Before/After care",Category:"Child Care and Child Development"},
        {Name: "Youth Enrichment Programs",Category:"Child Care and Child Development"},
        {Name: "Girl Empowerment",Category:"Youth/Teen Development"},
        {Name: "Leadership Development – girls/teens",Category:"Youth/Teen Development"},
        {Name: "STEM / STEAM / Tech",Category:"Youth/Teen Development"},
        {Name: "Teen Pregnancy",Category:"Youth/Teen Development"},
        {Name: "Academic advancement programs",Category:"Youth/Teen Development"},
        {Name: "Personal Financial Literacy",Category:"Youth/Teen Development"},
        {Name: "Girls' Career Exploration",Category:"Youth/Teen Development"},
        {Name: "Job skills and workforce readiness programs",Category:"Economic Empowerment"},
        {Name: "Job placement assistance / Career Counseling",Category:"Economic Empowerment"},
        {Name: "Financial literacy and management",Category:"Economic Empowerment"},
        {Name: "GED	Job Banks",Category:"Economic Empowerment"},
        {Name: "Job Fairs",Category:"Economic Empowerment"},
        {Name: "Leadership development – Women",Category:"Economic Empowerment"},
        {Name: "Community Service Provider",Category:"Economic Empowerment"},
        {Name: "Employer Training Program",Category:"Economic Empowerment"},
        {Name: "STEM/STEAM Program",Category:"Economic Empowerment"},
        {Name: "STEAM E3 (Employment, Entrepreneurship & Education)",Category:"Economic Empowerment"},
        {Name: "Non-traditional job training",Category:"Economic Empowerment"},
        {Name: "Clothing Closet / Work Wardrobes",Category:"Economic Empowerment"},
        {Name: "Transportation",Category:"Economic Empowerment"},
        {Name: "Women’s Empowerment 360˚",Category:"Economic Empowerment"},
        {Name: "Fitness Center / Classes",Category:"Health and Wellness"},
        {Name: "Aquatics (General and Team Programs)",Category:"Health and Wellness"},
        {Name: "Swim Instruction",Category:"Health and Wellness"},
        {Name: "Wellness Education",Category:"Health and Wellness"},
        {Name: "Health screenings (breast, cervical, etc.)",Category:"Health and Wellness"},
        {Name: "Health Care Access",Category:"Health and Wellness"},
        {Name: "Infant Health",Category:"Health and Wellness"},
        {Name: "Maternal Health",Category:"Health and Wellness"},
        {Name: "Teen Outreach",Category:"Health and Wellness"},
        {Name: "HIV/AIDS outreach",Category:"Health and Wellness"},
        {Name: "Senior Wellness programming",Category:"Health and Wellness"},
        {Name: "Senior General programming",Category:"Health and Wellness"},
        {Name: "Substance Abuse – general",Category:"Health and Wellness"},
        {Name: "Substance Abuse - opioid",Category:"Health and Wellness"},
        {Name: "Intervention / Prevention",Category:"Health and Wellness"},
        {Name: "Food Pantry	Behavioral Health",Category:"Health and Wellness"},
        {Name: "Healthy Weight and Nutrition",Category:"Health and Wellness"},
      ]);
    });
};
